services:
  hexum:
    build: .
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:8-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: /bin/sh -c 'redis-server --requirepass "$${REDIS_PASSWORD}"'
    ports:
      - "6379:6379"