debug = true

[api]
host = "0.0.0.0"
port = 8080
protocol = "http"
docs_endpoint = "docs"

[postgresql]
pool_max_conn = 5
host = "0.0.0.0"
port = 5432
user = "kaucrow"
passwd = "postgres"
name = "dev"

[redis]
host = "localhost"
port = 6379
user = ""
passwd = ""
number = "0"